### ISSUE TITLE
[REQUEST] add few computational/scientific languages

### ISSUE THREAD

**Issue by kookma** [gera2ld/tw-prism#2]
Thank you for this great plugin!

- would you please add brushes for Fortran, Matlab, and Julia
- is there any way to reduce the size of plugin?

**Comment by gera2ld** [comment]
>     * would you please add brushes for Fortran, Matlab, and Julia

I will provide a tool to pick any languages you like soon.

>     * is there any way to reduce the size of plugin?

I think the only way to reduce the size is to drop languages that you don't need. Currently this plugin only includes minified and necessary code from PrismJS so it should be as small as possible.

**Comment by kookma** [comment]
Thank you very much!

**Comment by gera2ld** [comment]
FYI the DIY tool is available [here](https://gera2ld.github.io/tw-prism/diy.html).
